import { Exercise } from '../types';

export interface ExerciseTemplate {
  id: string;
  name: string;
  muscleGroup: 'Chest' | 'Back' | 'Legs' | 'Shoulders' | 'Arms' | 'Core' | 'Full Body' | 'Cardio';
  equipment: 'Barbell' | 'Dumbbell' | 'Bodyweight' | 'Cable' | 'Machine' | 'Kettlebell' | 'None';
  type?: 'strength' | 'cardio' | 'hiit' | 'mobility';
  defaultSets?: number;
  defaultReps?: number;
  defaultWeightKg?: number;
  instructions?: string;
  tip?: string;
}

export const standardExerciseCatalog: ExerciseTemplate[] = [
  // CARDIO, WALKING & RUNNING
  {
    id: 'tpl_walk_outdoor',
    name: 'Caminata / Andar al Aire Libre (GPS)',
    muscleGroup: 'Cardio',
    equipment: 'None',
    type: 'cardio',
    defaultSets: 1,
    defaultReps: 1,
    defaultWeightKg: 3.5,
    instructions: 'Marcha continua o paseo a ritmo constante al aire libre con seguimiento GPS.',
    tip: 'Mantén los hombros relajados y el abdomen activo durante la caminata.',
  },
  {
    id: 'tpl_walk_incline_treadmill',
    name: 'Caminata en Cinta con Inclinación (12-3-30)',
    muscleGroup: 'Cardio',
    equipment: 'Machine',
    type: 'cardio',
    defaultSets: 1,
    defaultReps: 1,
    defaultWeightKg: 2.5,
    instructions: 'Caminata en cinta con pendiente (8%-12% de inclinación) a velocidad moderada (4.5 - 5.5 km/h).',
    tip: 'No te agarres fuertemente a los manillares; bracea de forma natural para mayor quema calórica.',
  },
  {
    id: 'tpl_walk_active_recovery',
    name: 'Paseo de Recuperación Activa (LISS)',
    muscleGroup: 'Cardio',
    equipment: 'None',
    type: 'cardio',
    defaultSets: 1,
    defaultReps: 1,
    defaultWeightKg: 3.0,
    instructions: 'Paseo suave para reducir el cortisol, activar la circulación y favorecer la recuperación muscular.',
    tip: 'Mantén una respiración nasal relajada durante todo el trayecto.',
  },
  {
    id: 'tpl_run_outdoor',
    name: 'Carrera Exterior / Asfalto (GPS)',
    muscleGroup: 'Cardio',
    equipment: 'None',
    type: 'cardio',
    defaultSets: 1,
    defaultReps: 1,
    defaultWeightKg: 5.0,
    instructions: 'Carrera continua al aire libre. Mide distancia en km, ritmo y zonas cardíacas.',
    tip: 'Mantén una zancada fluida y respiración rítmica.',
  },
  {
    id: 'tpl_run_treadmill',
    name: 'Cinta de Correr (Treadmill)',
    muscleGroup: 'Cardio',
    equipment: 'Machine',
    type: 'cardio',
    defaultSets: 1,
    defaultReps: 1,
    defaultWeightKg: 4.0,
    instructions: 'Entrenamiento en cinta con control de velocidad e inclinación.',
    tip: 'Añade 1% de inclinación para simular la resistencia del viento exterior.',
  },
  {
    id: 'tpl_cardio_bike',
    name: 'Bicicleta Estática / Ciclo Indoor',
    muscleGroup: 'Cardio',
    equipment: 'Machine',
    type: 'cardio',
    defaultSets: 1,
    defaultReps: 1,
    defaultWeightKg: 10.0,
    instructions: 'Pedaleo continuo o por intervalos con resistencia progresiva.',
    tip: 'Ajusta la altura del sillín para evitar sobrecarga en rodillas.',
  },
  {
    id: 'tpl_cardio_rower',
    name: 'Remo Ergómetro (Concept2)',
    muscleGroup: 'Full Body',
    equipment: 'Machine',
    type: 'cardio',
    defaultSets: 3,
    defaultReps: 1,
    defaultWeightKg: 2.0,
    instructions: 'Potencia de piernas, bisagra de cadera y tracción con dorsales y brazos.',
    tip: '60% del impulso proviene de las piernas, 20% del core y 20% de los brazos.',
  },
  {
    id: 'tpl_cardio_elliptical',
    name: 'Elíptica / Escaladora (Stairmaster)',
    muscleGroup: 'Cardio',
    equipment: 'Machine',
    type: 'cardio',
    defaultSets: 1,
    defaultReps: 1,
    defaultWeightKg: 3.0,
    instructions: 'Cardio de bajo impacto articular con alto consumo calórico.',
    tip: 'Mantén el torso erguido sin apoyarte excesivamente en los manillares.',
  },
  {
    id: 'tpl_cardio_jump_rope',
    name: 'Salto de Comba / Cuerda Rápida',
    muscleGroup: 'Cardio',
    equipment: 'None',
    type: 'cardio',
    defaultSets: 3,
    defaultReps: 100,
    defaultWeightKg: 0,
    instructions: 'Saltos sobre la punta de los pies con giro de muñeca suave.',
    tip: 'Mantén los codos pegados al cuerpo y rebota elásticamente.',
  },

  // PECHO (CHEST)
  {
    id: 'tpl_bench_press_barbell',
    name: 'Press de Banca Plano con Barra',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeightKg: 60,
    instructions: 'Retracción escapular, barra al esternón inferior y empuje vertical.',
    tip: 'Aprieta los pies contra el suelo para transferir fuerza (Leg Drive).',
  },
  {
    id: 'tpl_incline_bench_dumbbell',
    name: 'Press Inclinado con Mancuernas (30°)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 22,
    instructions: 'Banco a 30°, enfatiza la porción clavicular del pectoral.',
    tip: 'Baja sintiendo el estiramiento profundo sin rebotar.',
  },
  {
    id: 'tpl_chest_dips',
    name: 'Fondos en Paralelas para Pecho',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 0,
    instructions: 'Inclina el torso 30° hacia adelante para focalizar pectoral inferior.',
  },
  {
    id: 'tpl_cable_crossover',
    name: 'Cruces de Poleas (Cables Crossover)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 15,
    instructions: 'Abraza el movimiento manteniendo una ligera flexión de codos.',
  },

  // ESPALDA (BACK)
  {
    id: 'tpl_deadlift_barbell',
    name: 'Peso Muerto Convencional con Barra',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 4,
    defaultReps: 5,
    defaultWeightKg: 100,
    instructions: 'Barra pegada a las espinillas, espalda neutra y bloqueo con glúteos.',
  },
  {
    id: 'tpl_pullups_strict',
    name: 'Dominadas Pronas Estrictas',
    muscleGroup: 'Back',
    equipment: 'Bodyweight',
    type: 'strength',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeightKg: 0,
    instructions: 'Desde bloqueo completo de brazos hasta pasar la barbilla por encima de la barra.',
  },
  {
    id: 'tpl_barbell_row',
    name: 'Remo con Barra Pendlay / 90°',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeightKg: 65,
    instructions: 'Torso paralelo al suelo, tracciona hacia la parte baja del esternón.',
  },
  {
    id: 'tpl_lat_pulldown',
    name: 'Jalón al Pecho en Polea Alta',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 55,
    instructions: 'Pecho erguido, tira con los codos hacia abajo y atrás.',
  },
  {
    id: 'tpl_seated_cable_row',
    name: 'Remo Gironda en Polea Baja',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 50,
    instructions: 'Agarre neutro cerrado, estira dorsal adelante y aprieta 1s atrás.',
  },

  // PIERNAS (LEGS)
  {
    id: 'tpl_back_squat_barbell',
    name: 'Sentadilla Trasera con Barra (Back Squat)',
    muscleGroup: 'Legs',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 4,
    defaultReps: 6,
    defaultWeightKg: 90,
    instructions: 'Pies al ancho de hombros, desciende por debajo de la paralela.',
  },
  {
    id: 'tpl_leg_press',
    name: 'Prensa Inclinada 45°',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 160,
    instructions: 'Baja controlado sin despegar la zona lumbar del respaldo.',
  },
  {
    id: 'tpl_romanian_deadlift',
    name: 'Peso Muerto Rumano con Mancuernas',
    muscleGroup: 'Legs',
    equipment: 'Dumbbell',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 28,
    instructions: 'Lleva la cadera hacia atrás sintiendo tensión máxima en isquiotibiales.',
  },
  {
    id: 'tpl_bulgarian_split_squat',
    name: 'Sentadilla Búlgara con Mancuernas',
    muscleGroup: 'Legs',
    equipment: 'Dumbbell',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 16,
    instructions: 'Pie trasero en banco, desciende verticalmente con la pierna delantera.',
  },
  {
    id: 'tpl_hip_thrust',
    name: 'Hip Thrust con Barra para Glúteos',
    muscleGroup: 'Legs',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 80,
    instructions: 'Espalda alta apoyada en banco, empuje de cadera y contracción de 2s arriba.',
  },
  {
    id: 'tpl_leg_extension',
    name: 'Extensión de Cuádriceps en Máquina',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 45,
    instructions: 'Extensión completa y pausa de 1 segundo en el punto de máxima contracción.',
  },
  {
    id: 'tpl_leg_curl',
    name: 'Curl Femoral Tumbado en Máquina',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 40,
    instructions: 'Flexiona las rodillas hacia los glúteos de forma controlada.',
  },

  // HOMBROS (SHOULDERS)
  {
    id: 'tpl_overhead_press',
    name: 'Press Militar de Pie con Barra (OHP)',
    muscleGroup: 'Shoulders',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 4,
    defaultReps: 6,
    defaultWeightKg: 45,
    instructions: 'Glúteos y abdomen contraídos, empuje vertical estricto.',
  },
  {
    id: 'tpl_lateral_raises',
    name: 'Elevaciones Laterales con Mancuernas',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbell',
    type: 'strength',
    defaultSets: 4,
    defaultReps: 15,
    defaultWeightKg: 10,
    instructions: 'Codos ligeramente flexionados, eleva hasta la altura de los hombros.',
  },
  {
    id: 'tpl_face_pull',
    name: 'Face Pull con Cuerda en Polea',
    muscleGroup: 'Shoulders',
    equipment: 'Cable',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeightKg: 25,
    instructions: 'Tira de la cuerda hacia los ojos abriendo las manos para rotación externa.',
  },

  // BRAZOS (ARMS)
  {
    id: 'tpl_bicep_barbell_curl',
    name: 'Curl de Bíceps con Barra Z',
    muscleGroup: 'Arms',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 30,
    instructions: 'Codos fijos pegados al torso, flexión estricta sin balanceo.',
  },
  {
    id: 'tpl_hammer_curl',
    name: 'Curl Martillo con Mancuernas (Braquial)',
    muscleGroup: 'Arms',
    equipment: 'Dumbbell',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 14,
    instructions: 'Agarre neutro con palmas mirándose entre sí.',
  },
  {
    id: 'tpl_tricep_rope_pushdown',
    name: 'Extensión de Tríceps en Polea con Cuerda',
    muscleGroup: 'Arms',
    equipment: 'Cable',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 25,
    instructions: 'Empuja hacia abajo y abre los extremos de la cuerda al final.',
  },
  {
    id: 'tpl_skull_crushers',
    name: 'Press Francés / Skull Crushers',
    muscleGroup: 'Arms',
    equipment: 'Barbell',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 25,
    instructions: 'Baja la barra Z hacia la frente flexionando solo los codos.',
  },

  // CORE (ABDOMEN)
  {
    id: 'tpl_hanging_leg_raise',
    name: 'Elevación de Piernas Colgado en Barra',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 0,
    instructions: 'Eleva las piernas rectas hasta 90° o tocar la barra sin balanceo.',
  },
  {
    id: 'tpl_cable_woodchopper',
    name: 'Cable Woodchopper (Oblícuos)',
    muscleGroup: 'Core',
    equipment: 'Cable',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 20,
    instructions: 'Rotación explosiva de torso con brazos estirados.',
  },
  {
    id: 'tpl_ab_wheel',
    name: 'Rueda Abdominal (Ab Wheel Rollout)',
    muscleGroup: 'Core',
    equipment: 'None',
    type: 'strength',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeightKg: 0,
    instructions: 'Extiende el cuerpo hacia adelante manteniendo la retroversión pélvica.',
  },
];

export function templateToExercise(template: ExerciseTemplate): Exercise {
  const isCardio = template.type === 'cardio' || template.muscleGroup === 'Cardio';
  const setsCount = template.defaultSets || 3;
  const targetReps = template.defaultReps || (isCardio ? 1 : 10);
  const targetWeight = template.defaultWeightKg || 0;

  const sets = Array.from({ length: setsCount }, (_, i) => ({
    id: `s_${Date.now()}_${i + 1}`,
    setNumber: i + 1,
    targetReps,
    actualReps: targetReps,
    targetWeightKg: targetWeight,
    actualWeightKg: targetWeight,
    completed: false,
    isWarmup: i === 0 && targetWeight > 40 && !isCardio,
  }));

  return {
    id: `ex_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    name: template.name,
    muscleGroup: template.muscleGroup,
    equipment: template.equipment,
    type: template.type || (isCardio ? 'cardio' : 'strength'),
    sets,
    restSeconds: isCardio ? 0 : 90,
    instructions: template.instructions,
    tip: template.tip,
  };
}
