import {
  UserProfile,
  WorkoutRoutine,
  CommunityChallenge,
  Achievement,
  LeaderboardUser,
  SmartwatchDevice,
  PushReminder,
  WorkoutHistoryEntry,
} from '../types';

/**
 * Creates a clean brand-new user profile with 0 stats, 0 XP, Level 1.
 */
export const createFreshUser = (id: string, name: string, email?: string): UserProfile => {
  const initial = name.trim() ? name.trim().charAt(0).toUpperCase() : 'U';
  return {
    id,
    name: name || (email ? email.split('@')[0] : 'Atleta FitQuest'),
    avatar: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(name || id)}&backgroundColor=06b6d4,3b82f6`,
    level: 1,
    xp: 0,
    currentLevelXp: 0,
    nextLevelXp: 250,
    rankTitle: 'Recluta Inicial',
    league: 'Bronze',
    leaguePoints: 0,
    stats: {
      totalWorkouts: 0,
      totalVolumeKg: 0,
      totalMinutes: 0,
      caloriesBurned: 0,
      currentStreak: 0,
      bestStreak: 0,
      duelsWon: 0,
      challengesCompleted: 0,
    },
    attributes: {
      strength: 10,
      endurance: 10,
      agility: 10,
      discipline: 10,
    },
    unlockedBadges: [],
    joinedAt: new Date().toISOString().split('T')[0],
    weightKg: 70.0,
    targetWeightKg: 70.0,
  };
};

/**
 * Clean fresh achievement list starting with 0 progress for new users.
 */
export const createFreshAchievements = (): Achievement[] => [
  {
    id: 'ach_first_workout',
    title: 'Primer Paso de Leyenda',
    description: 'Completa tu primer entrenamiento en la plataforma.',
    icon: 'Flame',
    category: 'consistency',
    tier: 'Bronze',
    currentProgress: 0,
    maxProgress: 1,
    unlocked: false,
    xpReward: 100,
    rewardTitle: 'Iniciado',
  },
  {
    id: 'ach_first_pr',
    title: 'Superando Límites',
    description: 'Establece tu primer récord personal (PR) en cualquier ejercicio.',
    icon: 'Trophy',
    category: 'strength',
    tier: 'Bronze',
    currentProgress: 0,
    maxProgress: 1,
    unlocked: false,
    xpReward: 150,
    rewardTitle: 'Rompedor de Marcas',
  },
  {
    id: 'ach_streak_3',
    title: 'Racha de Bronce',
    description: 'Entrena 3 días consecutivos sin romper la racha.',
    icon: 'Flame',
    category: 'consistency',
    tier: 'Bronze',
    currentProgress: 0,
    maxProgress: 3,
    unlocked: false,
    xpReward: 200,
    rewardTitle: 'Persistente',
  },
  {
    id: 'ach_streak_7',
    title: 'Semana de Hierro',
    description: 'Mantén una racha de 7 días consecutivos de entrenamiento.',
    icon: 'Flame',
    category: 'consistency',
    tier: 'Silver',
    currentProgress: 0,
    maxProgress: 7,
    unlocked: false,
    xpReward: 300,
    rewardTitle: 'Constante',
  },
  {
    id: 'ach_streak_30',
    title: 'Disciplina Absoluta',
    description: 'Mantén una racha activa de 30 días consecutivos.',
    icon: 'Zap',
    category: 'consistency',
    tier: 'Titan',
    currentProgress: 0,
    maxProgress: 30,
    unlocked: false,
    xpReward: 1200,
    rewardTitle: 'Inquebrantable',
  },
  {
    id: 'ach_duel_master',
    title: 'Gladiador de la Arena',
    description: 'Gana 10 duelos de entrenamiento social en vivo.',
    icon: 'Swords',
    category: 'social',
    tier: 'Gold',
    currentProgress: 0,
    maxProgress: 10,
    unlocked: false,
    xpReward: 600,
    rewardTitle: 'Campéon de Duelo',
  },
  {
    id: 'ach_tonnage_10k',
    title: 'Levantador de Montañas',
    description: 'Acumula más de 10,000 kg de volumen total levantado en tu historial.',
    icon: 'Shield',
    category: 'strength',
    tier: 'Silver',
    currentProgress: 0,
    maxProgress: 10000,
    unlocked: false,
    xpReward: 500,
    rewardTitle: 'Coloso de Acero',
  },
  {
    id: 'ach_smartwatch_sync',
    title: 'Atleta Cibernético',
    description: 'Sincroniza un smartwatch y completa 5 entrenamientos con monitoreo cardíaco en vivo.',
    icon: 'Watch',
    category: 'speed',
    tier: 'Silver',
    currentProgress: 0,
    maxProgress: 5,
    unlocked: false,
    xpReward: 350,
    rewardTitle: 'Bio-Sincronizado',
  },
  {
    id: 'ach_community_hero',
    title: 'Pilar Comunitario',
    description: 'Completa con éxito 3 retos comunitarios semanales.',
    icon: 'Crown',
    category: 'social',
    tier: 'Titan',
    currentProgress: 0,
    maxProgress: 3,
    unlocked: false,
    xpReward: 800,
    rewardTitle: 'Héroe Comunitario',
  },
];

export const defaultRoutines: WorkoutRoutine[] = [
  {
    id: 'rt_upper_strength',
    title: 'Torso Fuerza & Sobrecarga',
    description: 'Rutina de fuerza enfocada en banca, remo con barra y press militar con descansos controlados.',
    category: 'Strength',
    difficulty: 'Intermediate',
    durationMinutes: 50,
    estimatedCalories: 450,
    xpReward: 300,
    targetMuscles: ['Pectoral', 'Espalda', 'Hombros', 'Tríceps'],
    tags: ['Fuerza', 'Barra', 'Sobrecarga'],
    exercises: [
      {
        id: 'ex_bench_press',
        name: 'Press de Banca Plano',
        muscleGroup: 'Chest',
        equipment: 'Barbell',
        restSeconds: 90,
        prKg: 0,
        instructions: 'Apoya bien los pies, retrae escápulas y baja la barra al esternón con control.',
        tip: 'Mantén los codos en ángulo de 45° a 75° con respecto al torso.',
        sets: [
          { id: 's1', setNumber: 1, targetReps: 12, actualReps: 12, targetWeightKg: 40, actualWeightKg: 40, completed: false, isWarmup: true },
          { id: 's2', setNumber: 2, targetReps: 10, actualReps: 10, targetWeightKg: 60, actualWeightKg: 60, completed: false },
          { id: 's3', setNumber: 3, targetReps: 8, actualReps: 8, targetWeightKg: 70, actualWeightKg: 70, completed: false },
          { id: 's4', setNumber: 4, targetReps: 6, actualReps: 6, targetWeightKg: 80, actualWeightKg: 80, completed: false },
        ],
      },
      {
        id: 'ex_barbell_row',
        name: 'Remo con Barra 45°',
        muscleGroup: 'Back',
        equipment: 'Barbell',
        restSeconds: 75,
        prKg: 0,
        instructions: 'Bisagra de cadera sólida, espalda neutra y tira de los codos hacia la cadera.',
        sets: [
          { id: 's5', setNumber: 1, targetReps: 10, actualReps: 10, targetWeightKg: 50, actualWeightKg: 50, completed: false },
          { id: 's6', setNumber: 2, targetReps: 10, actualReps: 10, targetWeightKg: 60, actualWeightKg: 60, completed: false },
          { id: 's7', setNumber: 3, targetReps: 8, actualReps: 8, targetWeightKg: 65, actualWeightKg: 65, completed: false },
        ],
      },
      {
        id: 'ex_military_press',
        name: 'Press Militar de Pie',
        muscleGroup: 'Shoulders',
        equipment: 'Barbell',
        restSeconds: 90,
        prKg: 0,
        instructions: 'Aprieta glúteos y abdomen, empuja verticalmente y pasa la cabeza al bloquear.',
        sets: [
          { id: 's8', setNumber: 1, targetReps: 10, actualReps: 10, targetWeightKg: 30, actualWeightKg: 30, completed: false },
          { id: 's9', setNumber: 2, targetReps: 8, actualReps: 8, targetWeightKg: 40, actualWeightKg: 40, completed: false },
          { id: 's10', setNumber: 3, targetReps: 6, actualReps: 6, targetWeightKg: 45, actualWeightKg: 45, completed: false },
        ],
      },
    ],
  },
  {
    id: 'rt_legs_hypertrophy',
    title: 'Pierna & Glúteos Titán',
    description: 'Enfoque biomecánico en sentadilla pesada, peso muerto rumano y prensa de piernas.',
    category: 'Hypertrophy',
    difficulty: 'Advanced',
    durationMinutes: 55,
    estimatedCalories: 550,
    xpReward: 350,
    targetMuscles: ['Cuádriceps', 'Isquiotibiales', 'Glúteos', 'Gemelos'],
    tags: ['Pierna', 'Hipertrofia', 'Volumen'],
    exercises: [
      {
        id: 'ex_squat',
        name: 'Sentadilla Trasera con Barra',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        restSeconds: 120,
        prKg: 0,
        instructions: 'Pies a la anchura de hombros, rompe el paralelo manteniendo el pecho alto.',
        tip: 'Inhala profundamente en diafragma (Bracing) antes de descender.',
        sets: [
          { id: 's11', setNumber: 1, targetReps: 10, actualReps: 10, targetWeightKg: 60, actualWeightKg: 60, completed: false, isWarmup: true },
          { id: 's12', setNumber: 2, targetReps: 8, actualReps: 8, targetWeightKg: 80, actualWeightKg: 80, completed: false },
          { id: 's13', setNumber: 3, targetReps: 8, actualReps: 8, targetWeightKg: 90, actualWeightKg: 90, completed: false },
        ],
      },
      {
        id: 'ex_romanian_dl',
        name: 'Peso Muerto Rumano',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        restSeconds: 90,
        prKg: 0,
        instructions: 'Flexión leve de rodilla, empuja la cadera hacia atrás hasta sentir estiramiento en isquios.',
        sets: [
          { id: 's14', setNumber: 1, targetReps: 10, actualReps: 10, targetWeightKg: 60, actualWeightKg: 60, completed: false },
          { id: 's15', setNumber: 2, targetReps: 10, actualReps: 10, targetWeightKg: 70, actualWeightKg: 70, completed: false },
        ],
      },
    ],
  },
  {
    id: 'rt_hiit_blitz',
    title: 'HIIT Spartan Cardio Blitz',
    description: 'Circuito metabólico de alta intensidad para quemar grasa y potenciar la resistencia cardiovascular.',
    category: 'HIIT',
    difficulty: 'Intermediate',
    durationMinutes: 30,
    estimatedCalories: 400,
    xpReward: 250,
    targetMuscles: ['Full Body', 'Cardio', 'Core'],
    tags: ['Cardio', 'Quema Grasa', 'HIIT'],
    exercises: [
      {
        id: 'ex_burpees',
        name: 'Burpees Explosivos',
        muscleGroup: 'Full Body',
        equipment: 'Bodyweight',
        restSeconds: 45,
        instructions: 'Pecho a suelo, salta extendiendo cadera y aplauso tras la nuca.',
        sets: [
          { id: 's16', setNumber: 1, targetReps: 15, actualReps: 15, targetWeightKg: 0, actualWeightKg: 0, completed: false },
          { id: 's17', setNumber: 2, targetReps: 15, actualReps: 15, targetWeightKg: 0, actualWeightKg: 0, completed: false },
        ],
      },
    ],
  },
];

export const defaultChallenges: CommunityChallenge[] = [
  {
    id: 'ch_weekly_volume_50k',
    title: 'Levantamiento de Titán Semanal',
    description: 'Levanta más de 20,000 kg acumulados entre todas tus sesiones esta semana.',
    category: 'volume',
    goalTarget: 20000,
    currentProgress: 0,
    unit: 'kg',
    participantsCount: 342,
    daysRemaining: 5,
    rewardXp: 500,
    rewardBadge: 'badge_titan_lift',
    joined: false,
    leaderboardTop: [
      { userId: 'u_1', name: 'Valeria Iron', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', score: 18450 },
      { userId: 'u_2', name: 'Diego Beast', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100', score: 16200 },
    ],
  },
  {
    id: 'ch_weekly_workouts_4',
    title: 'Consistencia 4 Días',
    description: 'Registra y finaliza al menos 4 entrenamientos completos antes del domingo.',
    category: 'workouts',
    goalTarget: 4,
    currentProgress: 0,
    unit: 'sesiones',
    participantsCount: 528,
    daysRemaining: 4,
    rewardXp: 350,
    rewardBadge: 'badge_consistency_4',
    joined: false,
    leaderboardTop: [
      { userId: 'u_3', name: 'Lucas Fit', avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100', score: 4 },
      { userId: 'u_4', name: 'Camila Cross', avatar: 'https://images.unsplash.com/photo-1534751516642-a171ed2c64ee?w=100', score: 3 },
    ],
  },
  {
    id: 'ch_weekly_calories_2000',
    title: 'Infierno Metabólico',
    description: 'Quema 2,000 calorías acumuladas durante tus entrenamientos activos.',
    category: 'calories',
    goalTarget: 2000,
    currentProgress: 0,
    unit: 'kcal',
    participantsCount: 412,
    daysRemaining: 6,
    rewardXp: 400,
    rewardBadge: 'badge_burner_2k',
    joined: false,
    leaderboardTop: [
      { userId: 'u_5', name: 'Sofia Lift', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100', score: 1780 },
      { userId: 'u_6', name: 'Mateo Runner', avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100', score: 1450 },
    ],
  },
];

export const defaultLeaderboard: LeaderboardUser[] = [
  { rank: 1, userId: 'u_top1', name: 'Valeria Iron', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', level: 22, xpEarned: 2450, streakDays: 24, league: 'Gold', workoutsThisWeek: 7 },
  { rank: 2, userId: 'u_top2', name: 'Diego Beast', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100', level: 19, xpEarned: 2180, streakDays: 15, league: 'Gold', workoutsThisWeek: 6 },
  { rank: 3, userId: 'u_top4', name: 'Lucas Fit', avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100', level: 16, xpEarned: 1720, streakDays: 12, league: 'Gold', workoutsThisWeek: 5, isFriend: true },
  { rank: 4, userId: 'u_top5', name: 'Camila Cross', avatar: 'https://images.unsplash.com/photo-1534751516642-a171ed2c64ee?w=100', level: 15, xpEarned: 1540, streakDays: 9, league: 'Gold', workoutsThisWeek: 4 },
  { rank: 5, userId: 'u_top6', name: 'Mateo Runner', avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100', level: 13, xpEarned: 1390, streakDays: 7, league: 'Gold', workoutsThisWeek: 4, isFriend: true },
];

export const defaultSmartwatch: SmartwatchDevice = {
  id: 'watch_user',
  name: 'Smartwatch Telemetría',
  brand: 'Apple Watch',
  status: 'connected',
  batteryLevel: 95,
  liveHeartRate: 125,
  hrvMs: 72,
  activeZone: 'Cardio',
  stepsToday: 4200,
  vo2max: 48.0,
  lastSyncTime: 'En vivo',
};

export const defaultPushReminders: PushReminder[] = [
  {
    id: 'rem_morning_workout',
    type: 'workout',
    title: '⚔️ ¡Hora de Entrenar!',
    message: 'Tu cuerpo está listo para romper marcas. Tu rutina de hoy te espera.',
    time: '07:30',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    enabled: true,
  },
  {
    id: 'rem_hydration',
    type: 'hydration',
    title: '💧 Recordatorio de Hidratación',
    message: 'Mantén tus músculos hidratados para maximizar la síntesis proteica.',
    time: '12:00',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    enabled: true,
  },
  {
    id: 'rem_streak_save',
    type: 'streak_save',
    title: '🔥 ¡Protege tu Racha!',
    message: 'Aún no has registrado actividad hoy. ¡Una sesión rápida salvará tu racha!',
    time: '19:00',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    enabled: true,
  },
];

export const defaultWorkoutHistory: WorkoutHistoryEntry[] = [];
